sudo: required
# Preinstall docker on Travis VM
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Install Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl
  - gcloud components update kubectl
  # Allow Google Cloud SDK to access Google Account through encrypted-IAM-Json (Need travis login)
  - gcloud auth actiavate-service-account --key-file service-account.json
