apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # ReadOnlyMany, ReadWriteMany, ReadWriteOnce 옵션 존재.
  accessModes:
    # Can be used by a single node to read&write
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
